import { extend } from 'flarum/extend';
import app from 'flarum/app';

import SitemapSettingsModal from 'recallfx/sitemap/components/SitemapSettingsModal';

// this name is automatically generated by flarum
app.initializers.add('recallfx-sitemap', app => {
  app.extensionSettings['recallfx-sitemap'] = () => app.modal.show(new SitemapSettingsModal());
});
