import { extend } from 'flarum/extend';
import app from 'flarum/app';

import SitemapSettingsModal from 'oberlo/oberloheader/components/SitemapSettingsModal';

// this name is automatically generated by flarum
app.initializers.add('recallfx-sitemap', app => {
  app.extensionSettings['recallfx-sitemap'] = () => app.modal.show(new SitemapSettingsModal());
});
